apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: $DOCKER_IO_REGISTRY/$BASE_IMAGE_NAMESPACE/$HEAPSTER_IMAGE
        command:
        - /heapster
        - --source=kubernetes:https://$KUBERNETES_SERVICE_HOST:443?inClusterConfig=true&useServiceAccount=true
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc.cluster.local:8086?retention=$INFLUXDB_RETENTION
        - --v=$ADDONS_LOG_VERBOSITY_LEVEL
      serviceAccountName: io-rancher-system
