#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

tar xvzf $DOWNLOAD/k8s.tar.gz --strip-components=3 kubernetes/server/bin/{kubelet,kube-proxy,kube-apiserver,kube-controller-manager,kube-scheduler,kubectl}
tar xvzf $DOWNLOAD/k8s.tar.gz kubernetes/kubernetes-src.tar.gz
tar xvzf kubernetes/kubernetes-src.tar.gz -C kubernetes --wildcards \
                                ./cluster/addons/dns/*.yaml.sed 

for t in kubernetes/cluster/addons/dns/*.yaml.sed; do
    sed -f dns.sed <${t} >${t%.sed} && rm ${t}
    echo ${t%.sed}
done

cp -r ../addon-templates/dashboard kubernetes/cluster/addons/
cp -r ../addon-templates/helm kubernetes/cluster/addons/

docker build -t ${REPO}/k8s:${TAG} .

echo Built ${REPO}/k8s:${TAG}
