#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package
# generate list of addon images
gen_versions

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

tar xvzf $DOWNLOAD/k8s.tar.gz --strip-components=3 kubernetes/server/bin/{kubelet,kube-proxy,kube-apiserver,kube-controller-manager,kube-scheduler,kubectl}
tar xvzf $DOWNLOAD/k8s.tar.gz kubernetes/kubernetes-src.tar.gz

mkdir -p kubernetes/cluster/addons

cp -r ../addon-templates/kubectl/* kubernetes/cluster/addons/

for t in kubernetes/cluster/addons/dns/*.yaml.sed; do
    sed -f dns.sed <${t} >${t%.sed} && rm ${t}
    echo ${t%.sed}
done

IMAGE=${REPO}/k8s:${TAG}
docker build -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
