apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: $GCR_IO_REGISTRY/$BASE_IMAGE_NAMESPACE/heapster-influxdb-amd64:v1.3.3
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      serviceAccountName: io-rancher-system
      volumes:
      - name: influxdb-storage
        $INFLUXDB_VOLUME
